/* Verification tooling: NODE_PATH=/path/to/playwright/node_modules node tests/frontend_scroll_regression.cjs */
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),BASE=process.env.CRE_BASE_URL||'http://127.0.0.1:8766';
const OUTPUT=path.join(ROOT,'artifacts','persistent-ui');fs.mkdirSync(OUTPUT,{recursive:true});
const chrome=process.env.CRE_BROWSER_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
(async()=>{const browser=await chromium.launch({headless:true,args:['--disable-gpu'],...(fs.existsSync(chrome)?{executablePath:chrome}:{})});
try{const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});const errors=[],requests=[];
async function capture(options){
 const bytes=await page.screenshot(options);
 const ink=await page.evaluate(async data=>{const img=new Image();img.src='data:image/png;base64,'+data;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const context=canvas.getContext('2d');context.drawImage(img,0,0);const rect=document.querySelector('h1').getBoundingClientRect();const pixels=context.getImageData(Math.round(rect.x),Math.round(rect.y),Math.min(300,Math.round(rect.width)),Math.round(rect.height)).data;let dark=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]<100&&pixels[i+1]<100&&pixels[i+2]<100)dark++;return dark},bytes.toString('base64'));
 assert(ink>100,'Application title must actually paint in '+path.basename(options.path));
}
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>requests.push(r.url()));
await page.goto(BASE);await page.waitForSelector('#patients tr');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(80);
const viewport=await page.evaluate(()=>({innerWidth,innerHeight,devicePixelRatio,scale:visualViewport.scale,zoom:getComputedStyle(document.body).zoom,transform:getComputedStyle(document.body).transform}));assert.equal(viewport.scale,1);assert.equal(viewport.zoom,'1');assert.equal(viewport.transform,'none');
const intro='See how decisions about clinical data change research results. Compare the results before and after checking corrections, diagnosis status, units and dates, then trace each decision back to the original record.';
assert.equal(await page.locator('#intro p').innerText(),intro);assert.equal(await page.locator('footer').innerText(),'Hari Sreedeth 2026 · GitHub');
assert.equal(await page.locator('#study-controls').getAttribute('data-persistent'),'false');
await page.evaluate(()=>{window.originalControls=document.getElementById('study-controls');window.originalThreshold=document.getElementById('threshold')});
const normal=await page.evaluate(()=>({metricsTop:document.getElementById('metrics').getBoundingClientRect().top+scrollY,slotHeight:document.getElementById('study-slot').getBoundingClientRect().height}));
const typography=await page.evaluate(()=>{const selectors=['body','h1','h2','#intro p','#study-controls p','input','button','th','.number','.label','.note','footer'];return Object.fromEntries(selectors.map(s=>{const style=getComputedStyle(document.querySelector(s));return [s,{font:style.fontFamily,size:style.fontSize,weight:style.fontWeight,style:style.fontStyle}]}))});assert.equal(typography.h1.size,'22px');assert.equal(typography.h1.weight,'600');assert.equal(typography['.number'].size,'52px');assert.equal(typography['.number'].weight,'400');assert.equal(typography['#intro p'].style,'normal');assert.equal(typography['.note'].style,'normal');assert.equal(typography.footer.size,'11px');assert(Object.values(typography).every(t=>t.font.includes('Inter')));
// Verify actual font glyphs, not merely the CSS family name.
const cdp=await page.context().newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const dom=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'#intro p'});const font=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});assert(font.fonts.length>0);assert(font.fonts.every(f=>f.isCustomFont&&f.familyName.includes('Inter')));
await capture({path:path.join(OUTPUT,'overview-initial.png')});
await page.evaluate(()=>scrollTo(0,document.getElementById('statistics-end').getBoundingClientRect().top+scrollY+20));await page.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='true');
async function checkPinned(){const bounds=await page.evaluate(()=>{const h=document.querySelector('header').getBoundingClientRect(),c=document.getElementById('study-controls').getBoundingClientRect(),title=document.querySelector('h1').getBoundingClientRect();return {header:{top:h.top,height:h.height,bottom:h.bottom},controls:{top:c.top,left:c.left,right:c.right,height:c.height,bottom:c.bottom},title:{x:title.x,y:title.y},width:innerWidth,height:innerHeight,sameControl:window.originalControls===document.getElementById('study-controls'),sameInput:window.originalThreshold===document.getElementById('threshold'),inputCount:document.querySelectorAll('#threshold').length}});assert.equal(bounds.header.top,0);assert(Math.abs(bounds.controls.top-bounds.header.bottom)<1);assert(bounds.controls.left>=0&&bounds.controls.right<=bounds.width);assert(bounds.controls.bottom<bounds.height*.5);assert(bounds.sameControl&&bounds.sameInput);assert.equal(bounds.inputCount,1);return bounds}
const pinned=await checkPinned();assert.equal(pinned.title.x,72);
const reserved=await page.evaluate(()=>({metricsTop:document.getElementById('metrics').getBoundingClientRect().top+scrollY,slotHeight:document.getElementById('study-slot').getBoundingClientRect().height}));assert(Math.abs(reserved.metricsTop-normal.metricsTop)<=1);assert(Math.abs(reserved.slotHeight-normal.slotHeight)<=1);
await page.locator('.compare').scrollIntoViewIfNeeded();await page.waitForTimeout(60);const comparisonTop=await page.locator('.compare h2').boundingBox();assert(comparisonTop.y>=pinned.controls.bottom);await capture({path:path.join(OUTPUT,'overview-scrolled.png')});
await page.locator('#days').fill('181');const updated=page.waitForResponse(r=>r.url().includes('days=181'));await page.locator('#apply').click();const r181=await(await updated).json();assert.equal(r181.counts.meets_threshold,3);await page.waitForFunction(()=>document.querySelector('#metrics .highlight .number').textContent==='3');assert.equal(await page.locator('#study-controls').getAttribute('data-persistent'),'true');
await page.locator('#days').fill('-1');const before=requests.filter(u=>u.includes('/api/report')).length;await page.locator('#apply').click();await page.waitForTimeout(100);assert.equal(requests.filter(u=>u.includes('/api/report')).length,before);assert.equal(await page.locator('#days').evaluate(el=>el.validity.valid),false);
const reset=page.waitForResponse(r=>r.url().includes('days=180'));await page.locator('#reset').click();assert.equal((await(await reset).json()).counts.meets_threshold,2);await page.waitForFunction(()=>document.querySelector('#metrics .highlight .number').textContent==='2');
await page.evaluate(()=>scrollTo(0,0));await page.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='false');assert.equal(await page.locator('#days').inputValue(),'180');assert.equal(await page.evaluate(()=>window.originalThreshold===document.getElementById('threshold')),true);
await page.locator('#see').click();await page.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='true');await page.waitForTimeout(50);await checkPinned();assert.equal(await page.locator('.node.stage').count(),40);const graphTop=await page.locator('.graph-toolbar').boundingBox();assert(graphTop.y>=(await checkPinned()).controls.bottom);await capture({path:path.join(OUTPUT,'lineage-initial.png')});
await page.selectOption('#patient-select','D');await page.locator('[data-inspect="D:stage:source"]').click();await page.locator('#disclosure summary').scrollIntoViewIfNeeded();await page.waitForTimeout(150);await checkPinned();const disclosure=await page.locator('#disclosure summary').boundingBox();assert(disclosure.y>=(await checkPinned()).controls.bottom);await page.locator('#disclosure summary').click();await page.selectOption('#inspect-select','Run information');await page.locator('#inspect-content').scrollIntoViewIfNeeded();await page.waitForTimeout(150);await checkPinned();assert(await page.evaluate(()=>scrollY>200));await capture({path:path.join(OUTPUT,'lineage-scrolled.png')});
// Recalculation from the pinned controls updates the graph and current inspector.
await page.locator('#days').fill('181');const traceResult=page.waitForResponse(r=>r.url().includes('days=181'));await page.locator('#apply').click();assert.equal((await(await traceResult).json()).counts.meets_threshold,3);await page.waitForFunction(()=>document.querySelector('[data-node="F:stage:measurement"]').textContent.includes('Day 181: included'));assert.equal(await page.locator('#patient-select').inputValue(),'D');
const traceReset=page.waitForResponse(r=>r.url().includes('days=180'));await page.locator('#reset').click();await traceReset;await page.waitForFunction(()=>document.querySelector('[data-node="F:stage:measurement"]').textContent.includes('outside window'));
await page.locator('#back').click();await page.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='false');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);await capture({path:path.join(OUTPUT,'narrow-overview-initial.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
await page.evaluate(()=>scrollTo(0,document.getElementById('statistics-end').getBoundingClientRect().top+scrollY+20));await page.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='true');await checkPinned();for(const selector of ['#threshold','#days','#apply','#reset']){const b=await page.locator(selector).boundingBox();assert(b.x>=0&&b.x+b.width<=390)}await capture({path:path.join(OUTPUT,'narrow-overview-scrolled.png')});
await page.locator('#trace-open').click();await page.waitForTimeout(80);await checkPinned();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await capture({path:path.join(OUTPUT,'narrow-lineage-initial.png'),fullPage:true});await page.locator('#disclosure summary').scrollIntoViewIfNeeded();await page.waitForTimeout(150);await checkPinned();await capture({path:path.join(OUTPUT,'narrow-lineage-scrolled.png')});
for(const id of ['error','graph-error'])assert.equal(await page.locator('#'+id).isVisible(),false);assert.deepEqual(errors,[]);const external=requests.filter(u=>/^https?:/.test(u)&&new URL(u).origin!==new URL(BASE).origin);assert.deepEqual(external,[]);assert(requests.some(u=>u.endsWith('/fonts/InterVariable.woff2')));
// Both Inter faces are embedded inside the self-contained snapshot.
const preview=await browser.newPage({viewport:{width:1920,height:1080}});const previewRequests=[];preview.on('request',r=>previewRequests.push(r.url()));preview.on('pageerror',e=>errors.push(e.message));await preview.goto('file://'+path.join(ROOT,'Preview.html'));await preview.evaluate(()=>document.fonts.ready);await preview.waitForSelector('#patients tr');assert.equal(await preview.locator('#apply').isDisabled(),true);await preview.locator('#see').click();await preview.waitForFunction(()=>document.getElementById('study-controls').dataset.persistent==='true');assert.equal(await preview.locator('.node.stage').count(),40);assert.equal(previewRequests.filter(u=>/^https?:/.test(u)).length,0);assert(await preview.evaluate(()=>document.fonts.check('400 14px Inter')));assert.deepEqual(errors,[]);await preview.close();
const result={viewport,typography,actualFonts:font.fonts,pinned,normal,reserved,localFontRequests:requests.filter(u=>u.includes('/fonts/')),externalRequests:external,errors,checks:['plain introduction and footer','actual local Inter glyphs','fixed title bounds and screenshot ink','sentinel activation and restoration','single shared input identity','preserved normal flow space','section scroll offsets','toolbar recalculation and reset','native validation','persistent lineage controls','narrow layouts','embedded snapshot fonts']};fs.writeFileSync(path.join(OUTPUT,'browser-checks.json'),JSON.stringify(result,null,2));console.log({viewport,actualFonts:font.fonts,pinned,errors,checks:result.checks});
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
